# Generated by Django 3.2 on 2022-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='peramalan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='ket1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='ket2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
