# Generated by Django 3.2 on 2022-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220330_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='ket2',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
