# Generated by Django 3.2 on 2022-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tabel_ket2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variabel', models.CharField(max_length=5, null=True)),
                ('mid', models.IntegerField(null=True)),
            ],
        ),
    ]
