# Generated by Django 3.2 on 2022-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_banding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banding',
        ),
        migrations.DeleteModel(
            name='Batas',
        ),
        migrations.AlterField(
            model_name='tabel',
            name='peramalan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
