# Generated by Django 4.0.2 on 2022-04-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220403_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmaksmin',
            old_name='dmaks',
            new_name='d1',
        ),
        migrations.RenameField(
            model_name='dmaksmin',
            old_name='dmin',
            new_name='d2',
        ),
    ]
