# Generated by Django 4.0.3 on 2022-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tabel_rata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rata', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tabel',
            name='rata',
        ),
    ]
