# Generated by Django 4.0.2 on 2022-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rata_remove_tabel_rata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='tanggal',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
