# Generated by Django 3.2 on 2022-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tabel_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defuzzyfikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr', models.CharField(max_length=5, null=True)),
                ('ns', models.CharField(max_length=30, null=True)),
                ('peram', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KelasInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.CharField(max_length=5, null=True)),
                ('batasatas', models.IntegerField(default=0, null=True)),
                ('batasbawah', models.IntegerField(default=0, null=True)),
                ('midpoint', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
