# Generated by Django 3.2 on 2022-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_defuzzyfikasi_kelasint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='data',
            field=models.IntegerField(null=True),
        ),
    ]
