# Generated by Django 3.2 on 2022-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_tabel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='ket1',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
